### ISSUE TITLE
CosmosFullNode: Pods aren't restarted when p2p addresses are ready

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/cosmos-operator#210]
Only one p2p service is being created, directed to the first pod-0 in the deployment.

Additionally, the external address is being set to 0.0.0.0:26656, which means the nodes cannot advertise how they can be reached for p2p.

A p2p service should be created for every chain node pod, and each should be configured with an external address of the service IP

**Comment by DavidNix** [comment]
This is working as designed, but perhaps the design needs tweaking. 

The user controls how many p2p services are created via: 

```
  service:
    # Creates N LoadBalancer services and exposes those public IPs in p2p.
    maxP2PExternalAddresses: 1
```

If you want a p2p service created for each pod, you can set this to some very large number. 

> A p2p service should be created for every chain node pod, and each should be configured with an external address of the service IP

I have to challenge this statement because of cloud provider costs and quotas. The current design allows the user to determine their costs. 

We default to 1 for SL deployments, so we don't over provision cloud provider resources (namely load balancers which cost $) and don't bump up against quotas (namely IP addresses).

> which means the nodes cannot advertise how they can be reached for p2p.

What's the risk of not advertising themselves for p2p and instead only being a "consumer" of p2p from other peers?

**Comment by DavidNix** [comment]
The other risk is our pods are not guaranteed to be persistent peers yet. Work involved with https://github.com/strangelove-ventures/cosmos-operator/issues/42 will fix that limitation.

**Comment by DavidNix** [comment]
Update: I'm not seeing the `external_address` set appropriately at all. It's always an empty string. Pulling this into the current sprint because it relates to https://github.com/strangelove-ventures/cosmos-operator/issues/21
